name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - name: Install dependencies
        run: |
          set -ex
          curl -O -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
          python get-poetry.py --yes
          rm -f get-poetry.py
          $HOME/.poetry/bin/poetry install
      - name: Copy env.example to .env
        run: |
          set -ex
          test -f env.example && cp -a env.example .env || echo "env.example doesn't exist. It's OK"
      - name: Test with pytest
        run: |
          set -ex
          $HOME/.poetry/bin/poetry run coverage run -m pytest
      - name: Convert coverage to XML
        run: |
          set -ex
          $HOME/.poetry/bin/poetry run coverage xml
      - name: Upload coverage to codecov
        env:
          CODECOV_TOKEN: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
        run: |
          bash <(curl -s https://codecov.io/bash)
