name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          set -ex
          pip install -r requirements.txt
      - name: Install pre-commit
        run: |
          set -ex
          pip install pre-commit
      - name: Test with pytest
        run: |
          set -ex
          pytest tests
